coverage:
  status:
    patch: off
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unit
        paths:
          - "src/main/java/com/gznznzjsn/inventoryservice/queryapi"
          - "src/main/java/com/gznznzjsn/inventoryservice/commandapi"
        branches:
          - main
        if_ci_failed: error
        informational: false
        only_pulls: false