spring:
  application:
    name: inventory-service
  config:
    import: optional:.env[.properties]

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL}
  instance:
    prefer-ip-address: true

server:
  port: 0
