spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://${APP_DATA_MONGODB_USERNAME}:${APP_DATA_MONGODB_PASSWORD}@${APP_DATA_MONGODB_HOST}:${APP_DATA_MONGODB_PORT}/tasks?authSource=${APP_DATA_MONGODB_AUTHENTICATION-DATABASE}
  jackson:
    default-property-inclusion: NON_NULL
  config:
    import: optional:.env[.properties]
  r2dbc:
    url: ${APP_R2DBC_URL}
    username: ${APP_DATASOURCE_USERNAME}
    password: ${APP_DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${APP_JDBC_URL}
    password: ${APP_DATASOURCE_PASSWORD}
    user: ${APP_DATASOURCE_USERNAME}
  graphql:
    graphiql:
      enabled: true
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  axonserver:
    servers: ${AXON_AXONSERVER_SERVERS}

settings:
  elasticsearch:
    port: ${ELASTICSEARCH_PORT}
    host: ${ELASTICSEARCH_HOST}
    equipment:
      name:
        slop: 1
        max-expansions: 10
      manufacturer:
        slop: 1
        max-expansions: 10
      description:
        slop: 2
        max-expansions: 10